web:
  build: .
  ports:
    - "8888:8888"
    - "35729:35729"
  volumes:
    - .:/app
  links:
    - db
  environment:
    NODE_ENV: development

db:
  image: mongo:latest
  ports:
    - "27017:27017"